In [1]:
import numpy as np 
from scipy.linalg import svd, eig 

In [2]:
A = np.array([
    [1,2,3],
    [2,3,4],
    [4,5,6]
])

A

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [6]:
U, s, Vt = svd(A)
sigma = np.zeros((A.shape[0], A.shape[1]))

sigma[:A.shape[0], :A.shape[0]] = np.diag(s)

n_elements = 2
sigma = sigma[:, :n_elements]
Vt = Vt[:n_elements, :]

B = U.dot(sigma.dot(Vt))
B

array([[1., 2., 3.],
       [2., 3., 4.],
       [4., 5., 6.]])

In [10]:
T1 = U.dot(sigma)
print('first transformation \n', T1)
T2 = A.dot(Vt.T)
print('final transformation \n', T2)

first transformation 
 [[-3.68472343 -0.65024091]
 [-5.37765907 -0.28422328]
 [-8.76353036  0.44781197]]
final transformation 
 [[-3.68472343 -0.65024091]
 [-5.37765907 -0.28422328]
 [-8.76353036  0.44781197]]
